import controller.exception.DeviceNotConnectedException
import controller.ChargerController

ChargerController = controller.ChargerController.ChargerController
DeviceNotConnectedError = controller.exception.DeviceNotConnectedException.DeviceNotConnectedException
